DROP TABLE RECORD;

DROP TABLE PAYMENT;

DROP TABLE INVENTORY;

DROP TABLE PRODUCT;

DROP TABLE EMPLOYE;

DROP TABLE SHOP;

DROP TABLE CATEGORY;

DROP TABLE CUSTOMER;

SET SERVEROUTPUT ON

-- CREATING TABLES 
CREATE TABLE CATEGORY
(
    ID INT NOT NULL,
    TITLE VARCHAR(30) NOT NULL,
    NOTE VARCHAR(100),
    PRIMARY KEY(ID)
);

CREATE TABLE CUSTOMER
(
    ID INT NOT NULL,
    F_NAME VARCHAR(30) NOT NULL,
    L_NAME VARCHAR(30) NOT NULL,
    CONTACT VARCHAR(15),
    COUNTRY VARCHAR(15),
    CITY VARCHAR(15),
    PRIMARY KEY(ID)
);

CREATE TABLE SHOP
(
    ID INT NOT NULL,
    BRANCH VARCHAR(30) NOT NULL,
    CONTACT VARCHAR(15),
    PRIMARY KEY(ID)
);

CREATE TABLE EMPLOYE
(
    ID INT NOT NULL,
    S_ID INT NOT NULL,
    E_ROLE NUMBER(1, 0) NOT NULL,
    F_NAME VARCHAR(30) NOT NULL,
    L_NAME VARCHAR(30) NOT NULL,
    SALARY NUMBER(8),
    CONTACT VARCHAR(15),
    JOINED_AT DATE,
    PRIMARY KEY(ID),
    FOREIGN KEY (S_ID) REFERENCES SHOP(ID)  ON DELETE CASCADE
);

CREATE TABLE PRODUCT
(
    ID INT NOT NULl,
    C_ID INT NOT NULL,
    TITLE VARCHAR(30) NOT NULL,
    PRICE NUMBER(10, 2) NOT NULL,
    COLOR VARCHAR(20),
    NOTE VARCHAR(100),
    PRIMARY KEY(ID),
    FOREIGN KEY (C_ID) REFERENCES CATEGORY (ID) ON DELETE CASCADE
);

CREATE TABLE INVENTORY(
    S_ID INT NOT NULL,
    P_ID INT NOT NULL,
    QUANTITY NUMBER(10, 0) NOT NULL,
    FOREIGN KEY (S_ID) REFERENCES SHOP(ID) ON DELETE CASCADE,
    FOREIGN KEY (P_ID) REFERENCES PRODUCT(ID) ON DELETE CASCADE
);

CREATE TABLE PAYMENT(
    ID INT NOT NULL,
    S_ID INT NOT NULL,
    C_ID INT NOT NULL,
    P_DATE DATE,
    TOTAL NUMBER(12, 2),
    PRIMARY KEY(ID),
    FOREIGN KEY (S_ID) REFERENCES SHOP(ID) ON DELETE CASCADE,
    FOREIGN KEY (C_ID) REFERENCES CUSTOMER(ID) ON DELETE CASCADE
);

CREATE TABLE RECORD(
    PRO_ID INT NOT NULL,
    PAY_ID INT NOT NULL,
    QUANTITY NUMBER(5, 0) NOT NULL,
    AMOUNT NUMBER(10, 2),
    FOREIGN KEY (PAY_ID) REFERENCES PAYMENT(ID) ON DELETE CASCADE,
    FOREIGN KEY (PRO_ID) REFERENCES PRODUCT(ID) ON DELETE CASCADE
);

DESCRIBE CATEGORY;
DESCRIBE CUSTOMER;
DESCRIBE SHOP;
DESCRIBE EMPLOYE;
DESCRIBE PRODUCT;
DESCRIBE INVENTORY;
DESCRIBE RECORD;