DROP FUNCTION AVG_SALARY;

SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION AVG_SALARY RETURN NUMBER IS
AVG_SAL EMPLOYE.SALARY%TYPE;
begin
  SELECT AVG(SALARY) INTO AVG_SAL
  FROM EMPLOYE;
  RETURN AVG_SAL;
end;
/