INSERT INTO CATEGORY (ID,TITLE,NOTE)
VALUES (0,'TECH','Technological accessories are included in this category.');
INSERT INTO CATEGORY (ID,TITLE,NOTE)
VALUES (1,'FOOD','Food products are included in this category.');
INSERT INTO CATEGORY (ID,TITLE,NOTE)
VALUES (2,'COSMETIC','Food products are included in this category.');
INSERT INTO CATEGORY (ID,TITLE,NOTE)
VALUES (3,'ACCESSORIES','Accessories are included in this category.');
INSERT INTO CATEGORY (ID,TITLE,NOTE)
VALUES (4,'CLOTHING','Clothings are included in this category.');
INSERT INTO CATEGORY (ID,TITLE,NOTE)
VALUES (5,'HOUSEHOLD','HOUSEHOLDS are included in this category.');


INSERT INTO SHOP(ID,BRANCH,CONTACT)
VALUES(0,'US','9989');
INSERT INTO SHOP(ID,BRANCH,CONTACT)
VALUES(1,'BD','6689');
INSERT INTO SHOP(ID,BRANCH,CONTACT)
VALUES(2,'IND','3389');


INSERT INTO CUSTOMER(ID,F_NAME,L_NAME,CONTACT,COUNTRY,CITY)
VALUES(0,'Bishal','roy','01911122220','India','Delhi');
INSERT INTO CUSTOMER(ID,F_NAME,L_NAME,CONTACT,COUNTRY,CITY)
VALUES(1,'Ranvir','Kapoor','01911122221','India','Mumbai');
INSERT INTO CUSTOMER(ID,F_NAME,L_NAME,CONTACT,COUNTRY,CITY)
VALUES(2,'Jami','Lul','01911122222','Bangladesh','Dhaka');
INSERT INTO CUSTOMER(ID,F_NAME,L_NAME,CONTACT,COUNTRY,CITY)
VALUES(3,'Mishu','Baidya','01911122223','Bangladesh','Khulna');
INSERT INTO CUSTOMER(ID,F_NAME,L_NAME,CONTACT,COUNTRY,CITY)
VALUES(4,'Finch','Russel','01911122224','US','Newyork');
INSERT INTO CUSTOMER(ID,F_NAME,L_NAME,CONTACT,COUNTRY,CITY)
VALUES(5,'Violet','Markey','01911122225','US','Chinatown');


INSERT INTO EMPLOYE (ID,S_ID,E_ROLE,F_NAME,L_NAME,CONTACT,SALARY,JOINED_AT)
VALUES (0,0,0,'Albert','Rishi','01911100000',6000,'10-JUNE-2010');
INSERT INTO EMPLOYE (ID,S_ID,E_ROLE,F_NAME,L_NAME,CONTACT,SALARY,JOINED_AT)
VALUES (1,0,0,'Albert','Sam','01911100001',5500,'10-JUNE-2020');
INSERT INTO EMPLOYE (ID,S_ID,E_ROLE,F_NAME,L_NAME,CONTACT,SALARY,JOINED_AT)
VALUES (2,0,0,'Vishal','Roy','01911100002',7000,'10-JULY-2015');
INSERT INTO EMPLOYE (ID,S_ID,E_ROLE,F_NAME,L_NAME,CONTACT,SALARY,JOINED_AT)
VALUES (3,1,0,'Uday','Roy','01911100003',6000,'10-JUNE-2013');
INSERT INTO EMPLOYE(ID,S_ID,E_ROLE,F_NAME,L_NAME,CONTACT,SALARY,JOINED_AT)
VALUES(4,1,0,'Tom','Holland','01911100004',10000,'10-JUNE-2014');
INSERT INTO EMPLOYE(ID,S_ID,E_ROLE,F_NAME,L_NAME,CONTACT,SALARY,JOINED_AT)
VALUES (5,1,0,'Tom','Holland','01911100005',12000,'10-JUNE-2016');
INSERT INTO EMPLOYE(ID,S_ID,E_ROLE,F_NAME,L_NAME,CONTACT,SALARY,JOINED_AT)
VALUES (6,2,0,'Tom','Holland','01911100006',9000,'10-JULY-2019');
INSERT INTO EMPLOYE(ID,S_ID,E_ROLE,F_NAME,L_NAME,CONTACT,SALARY,JOINED_AT)
VALUES (7,2,0,'Wanda','Vision','01911100007',11000,'10-JUNE-2020');
INSERT INTO EMPLOYE(ID,S_ID,E_ROLE,F_NAME,L_NAME,CONTACT,SALARY,JOINED_AT)
VALUES(8,2,0,'Jenny','Stash','01911100008',10500,'10-JUNE-2011');
INSERT INTO EMPLOYE(ID,S_ID,E_ROLE,F_NAME,L_NAME,CONTACT,SALARY,JOINED_AT)
VALUES(9,0,1,'Robert','Hiddelson','01911100010',25000,'10-JUNE-2009');
INSERT INTO EMPLOYE(ID,S_ID,E_ROLE,F_NAME,L_NAME,CONTACT,SALARY,JOINED_AT)
VALUES(10,1,1,'Alex','Sans','01911100011',23000,'10-JULY-2010');
INSERT INTO EMPLOYE(ID,S_ID,E_ROLE,F_NAME,L_NAME,CONTACT,SALARY,JOINED_AT)
VALUES(11,2,1,'Tony','Stark','01911100011',30000,'10-JUNE-2012');


INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(0,0,'Xiomi M3 Headphone',700,'BLACK','A bluetooth speaker');
INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(1,0,'Rappo keyboard',1000,'BLACK','A bluetooth keyboard');
INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(2,0,'HP Monitor',17000,'BLACK','24 inch monitor');
INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(3,0,'DELL Monitor',17000,'BLACK','24 inch monitor');
INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(4,1,'Kellox Oats',300,'','');
INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(5,1,'Coke',40,'','');
INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(6,1,'Juice',60,'','');
INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(7,1,'Rice',45,'','');
INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(8,1,'Butter',45,'','');
INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(9,3,'Basket',150,'','');
INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(10,3,'Chair',800,'','');
INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(11,3,'Table',1400,'','');
INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(12,3,'Box',200,'','');
INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(13,4,'Shirt',2000,'RED','');
INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(14,4,'Jeans',1500,'NAVY','');
INSERT INTO PRODUCT(ID,C_ID,TITLE,PRICE,COLOR,NOTE)
VALUES(15,4,'Polo shirt',800,'BLACK','');


INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,0,20);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,1,25);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,2,30);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,3,30);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,4,15);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,5,20);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,6,40);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,7,32);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,8,14);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,9,25);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,10,36);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,11,44);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,12,15);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,13,23);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,14,5);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(0,15,10);

INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(1,0,22);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(1,1,25);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(1,2,30);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(1,3,30);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(1,4,15);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(1,5,20);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(1,6,40);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(1,7,32);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(1,8,14);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(1,9,25);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(1,10,36);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(1,11,44);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(1,12,15);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(1,13,23);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,14,5);


INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,0,20);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,1,25);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,2,30);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,3,30);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,4,15);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,5,20);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,6,40);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,7,32);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,8,14);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,9,25);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,10,36);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,11,44);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,12,15);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,13,23);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(2,14,5);
INSERT INTO INVENTORY(S_ID,P_ID,QUANTITY)
VALUES(1,15,10);


INSERT INTO PAYMENT(ID,S_ID,C_ID)
VALUES (0,0,4);
INSERT INTO PAYMENT(ID,S_ID,C_ID)
VALUES (1,0,5);
INSERT INTO PAYMENT(ID,S_ID,C_ID)
VALUES (2,0,4);
INSERT INTO PAYMENT(ID,S_ID,C_ID)
VALUES (3,0,4);

INSERT INTO PAYMENT(ID,S_ID,C_ID)
VALUES (5,1,3);
INSERT INTO PAYMENT(ID,S_ID,C_ID)
VALUES (6,1,2);
INSERT INTO PAYMENT(ID,S_ID,C_ID)
VALUES (7,1,3);

INSERT INTO PAYMENT (ID,S_ID,C_ID)
VALUES (8,2,3);
INSERT INTO PAYMENT (ID,S_ID,C_ID)
VALUES (9,2,2);
INSERT INTO PAYMENT (ID,S_ID,C_ID)
VALUES (10,2,3);

-- -- FOR SHOP 1
INSERT INTO RECORD(PRO_ID,PAY_ID,QUANTITY)
VALUES (8,5,1);
INSERT INTO RECORD(PRO_ID,PAY_ID,QUANTITY)
VALUES (1,5,1);
INSERT INTO RECORD(PRO_ID,PAY_ID,QUANTITY)
VALUES (2,5,2);

INSERT INTO RECORD(PRO_ID,PAY_ID,QUANTITY)
VALUES (6,6,1);

INSERT INTO RECORD(PRO_ID,PAY_ID,QUANTITY)
VALUES (4,7,3);
INSERT INTO RECORD(PRO_ID,PAY_ID,QUANTITY)
VALUES (6,7,2);

-- -- FOR SHOP 2
INSERT INTO RECORD(PRO_ID,PAY_ID,QUANTITY)
VALUES (10,5,1);
INSERT INTO RECORD(PRO_ID,PAY_ID,QUANTITY)
VALUES (13,5,2);

INSERT INTO RECORD(PRO_ID,PAY_ID,QUANTITY)
VALUES (11,6,1);

INSERT INTO RECORD(PRO_ID,PAY_ID,QUANTITY)
VALUES (9,7,3);
INSERT INTO RECORD(PRO_ID,PAY_ID,QUANTITY)
VALUES (4,7,2);


SELECT * FROM CATEGORY;
SELECT * FROM EMPLOYE;
SELECT * FROM CUSTOMER;
SELECT * FROM SHOP;
SELECT * FROM PRODUCT;
SELECT * FROM INVENTORY;
SELECT * FROM PAYMENT;
SELECT * FROM RECORD;